### ISSUE TITLE
 Deploy static to Tencent CloudBase过程报错

### ISSUE THREAD

**Issue by LordonCN** [TencentCloudBase/cloudbase-action#1]
login success<br>
(node:5498) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.<br>
##[error]路径不存在或没有权限访问：/home/runner/work/Tcloser.github.io/Tcloser.github.io/dist

**Comment by binggg** [comment]
我查一下

**Comment by binggg** [comment]
@Tcloser 是公开的项目么，可以贴下地址么，另外，这个路径是否存在呢

**Comment by LordonCN** [comment]
已解决

**Comment by rayliao** [comment]
`Tcloser.github.io/Tcloser.github.io/dist`

路径为何会重复，我的也这样

**Comment by Hydra92** [comment]
> `Tcloser.github.io/Tcloser.github.io/dist`
> 
> 路径为何会重复，我的也这样

我也遇到了同样的问题，在这记录一下以提醒后来者
**修改版本**
找到你workflow file里的`uses: TencentCloudBase/cloudbase-action@v1`，将最后的`v1`改为最新的版本号，如`v1.1.1`。问题解决。
