### ISSUE TITLE
最近每次都部署失败

### ISSUE THREAD

**Issue by eallion** [TencentCloudBase/cloudbase-action#16]
通过 GitHub Actions 部署 Hugo 到 CloudBase 静态托管，每次都失败。

**Comment by eallion** [comment]
<https://github.com/eallion/eallion.com/actions>

**Comment by vinceying** [comment]
请问楼主解决了吗？我也是这个问题，问了兵哥说是 `GIithub的 Runner 的网络连国内有时不太稳，他们机器都在海外，没有国内节点` 。

**Comment by eallion** [comment]
@vinceying 时好时坏，不能频繁部署。我想应该也是网络原因，基本上都是 Timeout errors。

**Comment by TonyWu3027** [comment]
看了一下[文档](https://docs.github.com/en/actions/hosting-your-own-runners)，最优解可能是自己host一台在国内的机子作为runner。我们项目下一个sprint会试一下这个方案，目前看应该可行

**Comment by linjiejim** [comment]
**因为超时导致部署不成功时，Action任务仍然为成功**

现象：当Action被触发并部署时，因为超时导致失败，但是最后Action的结果是成功的。
预期：当超时部署失败时，Action任务为失败。

这个现象会导致Github没有通知部署失败。请问是否有解决方法？

![Screen Shot 2022-05-11 at 4 56 29 PM](https://user-images.githubusercontent.com/18286145/167811667-00dcb955-24ea-4f06-abec-4bfdd846286b.png)

**Comment by binggg** [comment]
@linjiejim 使用 v2.0.1 版本
https://github.com/marketplace/actions/tencent-cloudbase-github-action?version=v2.0.1

有个PR解决了这个问题 https://github.com/TencentCloudBase/cloudbase-action/pull/27
