### ISSUE TITLE
希望能增加广州地区的环境

### ISSUE THREAD

**Issue by tootal** [TencentCloudBase/cloudbase-action#17]
部署时出现错误：

> Environment *** not found

猜测可能是广州地区环境的原因。

地址：https://github.com/tootal/world/runs/1660353814

**Comment by h7ml** [comment]
+1 使用广州地区环境部署的一直有这个问题，后来改为上海地区就好了

**Comment by binggg** [comment]
广州地区可以部署，可以在使用 V2 版，cloudbaserc.json 里指定region 为gz
