### ISSUE TITLE
staitcIgnore在 V2 版本去掉了吗？

### ISSUE THREAD

**Issue by pxxyyz** [TencentCloudBase/cloudbase-action#22]
如题

**Comment by binggg** [comment]
v2 版本的配置变成配置文件了

https://github.com/TencentCloudBase/cloudbase-action#%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6

相同的功能配置在这里

https://docs.cloudbase.net/framework/plugins/framework-plugin-website.html#ignore

**Comment by pxxyyz** [comment]
好的，非常感谢😀
