### ISSUE TITLE
目前能支持广州的环境吗

### ISSUE THREAD

**Issue by cayzlh** [TencentCloudBase/cloudbase-action#23]
使用GitHub action 部署静态网站的时候提示：`there is no normal environment`。

不知道是不是环境的原因：

<img width="658" alt="image" src="https://user-images.githubusercontent.com/12791269/110134144-0a258000-7e08-11eb-875f-561eb1548086.png">

**Comment by binggg** [comment]
配置文件中可以配置一下地域



---原始邮件---
发件人: "Ant丶"<notifications@github.com&gt;
发送时间: 2021年3月5日(周五) 晚上11:11
收件人: "TencentCloudBase/cloudbase-action"<cloudbase-action@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [TencentCloudBase/cloudbase-action] 目前能支持广州的环境吗 (#23)




 
使用GitHub action 部署静态网站的时候提示：there is no normal environment。
 
不知道是不是环境的原因：

**Comment by cayzlh** [comment]
> 配置文件中可以配置一下地域
> […](#)
配置什么属性呢， 有没有demo看下，

**Comment by yaonyan** [comment]
> 请仔细看下 CLI 配置文件的文档：https://docs.cloudbase.net/cli-v1/config.html#zi-duan
```diff
 {
   "version": "2.0",
   "envId": "xxx",
+  "region": "yourRegion",
 }
```
@cayzlh

**Comment by cayzlh** [comment]
收到。

**Comment by cayzlh** [comment]
我使用下面的配置部署之后变成了云环境里面的一个应用。。

```json
{
  "envId": "{{envId}}",
  "version": "2.0",
  "region": "ap-guangzhou",
  "framework": {
    "name": "diary",
    "plugins": {
      "hexo": {
        "use": "@cloudbase/framework-plugin-website",
        "inputs": {
          "outputPath": "./public",
          "cloudPath": "/diary",
          "ignore": [".git", ".github", "node_modules", "cloudbaserc.js"]
        }
      }
    }
  }
}
```

如果我想达到的预期只是部署静态网站托管的话， 需要怎么配置呢。 

@binggg @beetcb

**Comment by yaonyan** [comment]
@cayzlh V2 暂时不支持
> 我使用下面的配置部署之后变成了云环境里面的一个应用。。

虽然可以实现，但是这就需要本地构建再上传输出文件夹到 GitHub；我认为 CloudBase Framework （也就是目前 V2 版本）是更好的解决方案，我们在本地只需要直接写代码就好 💪，构建交给 GitHub

**Comment by cayzlh** [comment]
> @cayzlh V2 暂时不支持
> 
> > 我使用下面的配置部署之后变成了云环境里面的一个应用。。
> 
> 虽然可以实现，但是这就需要本地构建再上传输出文件夹到 GitHub；我认为 CloudBase Framework （也就是目前 V2 版本）是更好的解决方案，我们在本地只需要直接写代码就好 💪，构建交给 GitHub

了解；
那，部署成一个应用之后， 可以将内容再部署到静态网站托管的文件管理里面吗。 

V1.1.1 好像不支持配置`region`

**Comment by yaonyan** [comment]
> 那，部署成一个应用之后， 可以将内容再部署到静态网站托管的文件管理里面吗。

我不太能理解这句话，好久没用过静态网站托管了 🤔，ping 一下 @binggg 吧

**Comment by cayzlh** [comment]
> 我不太能理解这句话，好久没用过静态网站托管了 🤔，ping 一下 @binggg 吧

没事， 我来研究一下CloudBase Framework。。
