### ISSUE TITLE
执行时日志提示： 请输入应用唯一标识 

### ISSUE THREAD

**Issue by maYunLaoXi** [TencentCloudBase/cloudbase-action#25]
如图
![](https://gitee.com/maYunLaoXi/image/raw/master/blog/2021/WeChat3928d759ddc7543c1821bea82a244ba2.png)
![](https://gitee.com/maYunLaoXi/image/raw/master/blog/2021/WeChat49795edc440ad32655fcc29d8a8c82cd.png)

**Comment by binggg** [comment]
可以在 `framework.name` 字段设置下应用标识
https://docs.cloudbase.net/framework/config.html#name

**Comment by maYunLaoXi** [comment]
已经解决了，项目直接改了之前的action,看了一些网上的博客都是用的老版本，或者是上海的服务器。记下了一些要点
[http://www.yingyinbi.com/frontEnd/js/release-blog-by-githubactions-at-tencent.html](http://www.yingyinbi.com/frontEnd/js/release-blog-by-githubactions-at-tencent.html)
