### ISSUE TITLE
Missing cloudbase configuration file

### ISSUE THREAD

**Issue by shangdev** [TencentCloudBase/cloudbase-action#29]
用于 Hexo 自动部署。

报错信息
![image](https://user-images.githubusercontent.com/15621520/136884510-5d4e6020-1e8e-44b5-82dd-56833798ddeb.png)

workflow 文件
![image](https://user-images.githubusercontent.com/15621520/136884542-5ca2d798-b90f-4ae8-a553-52ba3dbf2870.png)

请问cloudbase configuration是什么？

**Comment by youzipi** [comment]
@shangdev 
请问是怎么解决的，报了同样的错

**Comment by youzipi** [comment]
> @shangdev 请问是怎么解决的，报了同样的错

找到了，加个 cloudbaserc.json 文件
